"""
deploy_space.py — push the app (and optionally the vector store) from this repo to Hugging Face.

Two HF repos are involved:
    Space   hereIcome/filings-rag         code only; every commit triggers a rebuild
    Dataset hereIcome/filings-rag-index   the chroma store + filing-periods.json, downloaded by serve.py at startup

What a deploy does:
    1. assemble a build folder (deploy/.build/space):
         serve.py, app/*.py, pipeline/*.py        copied from the repo
         README.md                                deploy/space/README.md (Space config frontmatter)
         requirements.txt                         generated from ./requirements.txt with the pins HF
                                                  installs itself commented out (see HF_PROVIDED)
    2. set the Space's public variables (INDEX_REPO, LANGFUSE_BASE_URL, LANGFUSE_TRACING_ENVIRONMENT)
    3. upload the build folder as one commit; code files no longer in the repo are deleted on the Space
    4. optionally watch the build and print the run/build log tail on failure

Secrets (OPENAI_API_KEY, LANGFUSE_PUBLIC_KEY, LANGFUSE_SECRET_KEY) are NOT set here — add them once in
the Space settings UI. HF_TOKEN (write access) is read from .env.

Usage (from the project root):
    venv/bin/python deploy/deploy_space.py --dry-run              # build folder only, nothing uploaded
    venv/bin/python deploy/deploy_space.py                        # deploy code
    venv/bin/python deploy/deploy_space.py --watch                # deploy + wait for RUNNING / error
    venv/bin/python deploy/deploy_space.py --index --watch        # re-export + upload vector store, then deploy
    venv/bin/python deploy/deploy_space.py --space me/other-space --index-repo me/other-index
"""

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path

import httpx
from dotenv import load_dotenv
from huggingface_hub import HfApi

ROOT = Path(__file__).resolve().parent.parent
DEPLOY_DIR = ROOT / "deploy"
BUILD_DIR = DEPLOY_DIR / ".build" / "space"

SPACE = "hereIcome/filings-rag"
INDEX_REPO = "hereIcome/filings-rag-index"

# copied into the Space; globs relative to ROOT
CODE_FILES = ["serve.py", "app/*.py", "pipeline/*.py"]

# the Gradio SDK installs these itself; pinning them too breaks pip's resolver
# (gradio[mcp] needs pydantic<=2.12.5, gradio comes from sdk_version in README.md)
HF_PROVIDED = {"gradio", "pydantic", "uvicorn"}

DONE_STAGES = {"RUNNING", "RUNTIME_ERROR", "BUILD_ERROR", "CONFIG_ERROR", "PAUSED", "STOPPED"}


# ---------------------------------------------------------------------------
# 1. build folder
# ---------------------------------------------------------------------------
def space_requirements(src):
    out = ["# generated by deploy/deploy_space.py from requirements.txt — do not edit on the Space"]
    for line in src.read_text().splitlines():
        name = re.split(r"[=<>!~\[ ]", line.strip(), maxsplit=1)[0].lower()
        out.append(f"# {line.strip()}    (provided by HF Gradio SDK)" if name in HF_PROVIDED else line)
    return "\n".join(out) + "\n"


def build():
    if BUILD_DIR.exists():
        shutil.rmtree(BUILD_DIR)
    BUILD_DIR.mkdir(parents=True)

    files = sorted({p for pattern in CODE_FILES for p in ROOT.glob(pattern)})
    for src in files:
        dst = BUILD_DIR / src.relative_to(ROOT)
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)
    shutil.copy2(DEPLOY_DIR / "space" / "README.md", BUILD_DIR / "README.md")
    (BUILD_DIR / "requirements.txt").write_text(space_requirements(ROOT / "requirements.txt"))

    print(f"build folder: {BUILD_DIR.relative_to(ROOT)}")
    for p in sorted(BUILD_DIR.rglob("*")):
        if p.is_file():
            print(f"  {p.relative_to(BUILD_DIR)}")


# ---------------------------------------------------------------------------
# 2-3. upload
# ---------------------------------------------------------------------------
def upload_index(index_repo):
    """Re-export the nomic collection and push it to the dataset repo (pipeline/export_index.py)."""
    subprocess.run(
        [sys.executable, str(ROOT / "pipeline" / "export_index.py"), "--upload", index_repo],
        check=True,
    )


def deploy(api, space, index_repo, message):
    api.create_repo(space, repo_type="space", space_sdk="gradio", exist_ok=True)
    variables = {
        "INDEX_REPO": index_repo,
        "LANGFUSE_BASE_URL": os.getenv("LANGFUSE_BASE_URL", "https://cloud.langfuse.com"),
        "LANGFUSE_TRACING_ENVIRONMENT": "prod",
    }
    for key, value in variables.items():
        api.add_space_variable(space, key, value)
    print(f"variables set: {', '.join(variables)}")

    commit = api.upload_folder(
        repo_id=space,
        repo_type="space",
        folder_path=str(BUILD_DIR),
        commit_message=message,
        ignore_patterns=["**/__pycache__/**", "data/**"],
        # remove code on the Space that no longer exists locally (never touches data or .gitattributes)
        delete_patterns=["*.py", "app/**", "pipeline/**"],
    )
    print(f"commit: {commit.commit_url}")


# ---------------------------------------------------------------------------
# 4. watch
# ---------------------------------------------------------------------------
def log_tail(space, kind, token, lines=40):
    """Last lines of the build or run log (HF streams them as server-sent events)."""
    out = []
    url = f"https://huggingface.co/api/spaces/{space}/logs/{kind}"
    try:
        with httpx.stream("GET", url, headers={"Authorization": f"Bearer {token}"}, timeout=15) as r:
            for line in r.iter_lines():
                if line.startswith("data:"):
                    try:
                        out.append(json.loads(line[5:])["data"].rstrip())
                    except (ValueError, KeyError):
                        out.append(line[5:])
    except httpx.ReadTimeout:
        pass  # stream stays open while the Space is alive; a timeout just means we have everything so far
    return [l for l in out if l.strip()][-lines:]


def watch(api, space, token, timeout_s=1200):
    time.sleep(10)  # let HF pick up the commit before the first status read
    started, last = time.time(), None
    while time.time() - started < timeout_s:
        runtime = api.get_space_runtime(space)
        if runtime.stage != last:
            print(f"{time.strftime('%X')}  {runtime.stage}")
            last = runtime.stage
        if runtime.stage in DONE_STAGES:
            break
        time.sleep(15)
    else:
        print("timed out waiting for the Space")
        return False

    if runtime.stage == "RUNNING":
        subdomain = space.replace("/", "-").lower()
        print(f"live: https://{subdomain}.hf.space   api: https://{subdomain}.hf.space/rag/docs")
        return True

    kind = "build" if runtime.stage in {"BUILD_ERROR", "CONFIG_ERROR"} else "run"
    print((runtime.raw.get("errorMessage") or "")[:500])
    print(f"\n--- {kind} log tail ---")
    print("\n".join(log_tail(space, kind, token)))
    return False


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--space", default=SPACE, help="Space repo id")
    ap.add_argument("--index-repo", default=INDEX_REPO, help="dataset repo id holding the vector store")
    ap.add_argument("--index", action="store_true", help="re-export and upload the vector store first")
    ap.add_argument("--dry-run", action="store_true", help="assemble the build folder, upload nothing")
    ap.add_argument("--watch", action="store_true", help="wait for the Space to finish building")
    ap.add_argument("-m", "--message", default="Deploy from deploy/deploy_space.py", help="commit message")
    args = ap.parse_args()

    build()
    if args.dry_run:
        return

    load_dotenv(ROOT / ".env")
    token = os.getenv("HF_TOKEN")
    if not token:
        sys.exit("HF_TOKEN missing in .env (needs write access)")
    api = HfApi(token=token)

    if args.index:
        upload_index(args.index_repo)
    deploy(api, args.space, args.index_repo, args.message)
    print("reminder: secrets OPENAI_API_KEY, LANGFUSE_PUBLIC_KEY, LANGFUSE_SECRET_KEY live in the Space settings UI")

    if args.watch and not watch(api, args.space, token):
        sys.exit(1)


if __name__ == "__main__":
    main()
